package domain.dtos.cliente

/**
 * Todos os tipos de informaçao que o cliente pode enviar para o servidor
 */
enum class TIPO_EVENTO_CLIENTE(val nome: String) {
    ABORTAR_DESLIGAMENTO("ABORTAR_DESLIGAMENTO"),
    AGENDAR_DESLIGAMENTO("AGENDAR_DESLIGAMENTO"),
    ACAO_REPRODUZIR_GRAVACAO("ACAO_REPRODUZIR_GRAVACAO"),
    ACAO_PARAR_REPRODUCAO("ACAO_PARAR_REPRODUCAO"),
    ACAO_ABORTAR_GRAVACAO("ACAO_ABORTAR_GRAVACAO"),
    ACAO_PARAR_GRAVACAO("ACAO_PARAR_GRAVACAO"),
    ACAO_GRAVAR("ACAO_GRAVAR"),
    MOUSE_CLICK_ESQ("MOUSE_CLICK_ESQ"), // toque no mousepad e clique no botao esquerdo do mouse são sempre interpretados da mesma forma
    MOUSE_CLICK_DIR("MOUSE_CLICK_DIR"),
    MOUSE_CLICK_CEN("MOUSE_CLICK_CEN"),
    MOUSE_MOVE("MOUSE_MOVE"),
    MOUSE_SCROLL("MOUSE_SCROLL"),
    PAD_CLICK_TWO_FINGERS("PAD_CLICK_TWO_FINGERS"),
    PAD_LONG_CLICK("PAD_LONG_CLICK"),
    VOLUME_MAIS("VOLUME_MAIS"),
    VOLUME_MENOS("VOLUME_MENOS"),
    NONE("NONE"),
}